src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LocationRepository::class)
 */
class Location
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $l_name;

    /**
     * @ORM\Column(type="decimal", precision=8, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLName(): ?string
    {
        return $this->l_name;
    }

    public function setLName(string $l_name): self
    {
        $this->l_name = $l_name;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use App\Entity\Location;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LocationController extends AbstractController
{
    #[Route('/Addlocation', name: 'Addlocation')]
    public function addAction()

    {



        // you can fetch the EntityManager via $this->getDoctrine()

        // or you can add an argument to your action: createAction(EntityManagerInterface $em)

        $em = $this->getDoctrine()->getManager();

        $Location = new Location(); // here we will create an object from our class Product.

        $Location->setLName('New Location'); // in our Location class we have a set function for each column in our db

        $Location->setPrice(3000);
        $Location->setDescription('Lorem ipsum loc.');


        // tells Doctrine you want to (eventually) save the Location (no queries yet)

        $em->persist($Location);

        // actually executes the queries (i.e. the INSERT query)

        $em->flush();

        return new Response('Saved new location with id ' . $Location->getId());
    }
    #[Route('/standard2', name: 'standard2')]
    public function showAll()
    {
        $locations = $this->getDoctrine()->getRepository(Location::class)->findAll();
        return $this->render('location/index.html.twig', array("locations" => $locations));
    }
}

src/Controller/StandardController.php
<?php

namespace App\Controller;

use App\Entity\Location;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StandardController extends AbstractController
{
    #[Route('/standard', name: 'standard')]
    public function index(): Response
    {
        $locations = $this->getDoctrine()->getRepository(Location::class)->findAll();
        return $this->render('standard/index.html.twig', [
            'controller_name' => 'StandardController', "locations" => $locations
        ]);
    }
    #[Route('/about', name: 'about')]
    public function aboutFunct()
    {
        return $this->render('standard/about.html.twig', []);
    }
    #[Route('/news', name: 'news')]
    public function newsFunct()
    {
        return $this->render('standard/news.html.twig', []);
    }
    #[Route('/contact', name: 'contact')]
    public function contactFunct()
    {
        return $this->render('standard/contact.html.twig', []);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		{# Run `composer require symfony/webpack-encore-bundle`
		           and uncomment the following Encore helpers to start using Symfony UX #}
		{% block stylesheets %}
			{#{{ encore_entry_link_tags('app') }}#}
		{% endblock %}

		{% block javascripts %}
			{#{{ encore_entry_script_tags('app') }}#}
		{% endblock %}
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	</head>
	<body>
		{{include('components/navbar.html.twig')}}
		{% block body %}{% endblock %}

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	</body>
</html>

templates/components/navbar.html.twig
<nav class="nav">
	<a class="nav-link active" aria-current="page" href="/standard">Home</a>
	<a class="nav-link" href="/news">News</a>
	<a class="nav-link" href="/contact">Contact</a>
	<a class="nav-link" href="/about">About</a>
</nav>

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Locations
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
		<ul>
			{% for location in locations %}

				<li>Location:{{location.lName}}, Price:{{location.price}}, Description
					{{location.description}}
				</li>
			{% endfor %}

		</ul>

	</div>
{% endblock %}

templates/standard/about.html.twig
{% extends 'base.html.twig' %}
{% block title %}About us
{% endblock %}
{% block body %}
	<h1 class="text-center">About us</h1>

{% endblock %}

templates/standard/contact.html.twig
{% extends 'base.html.twig' %}
{% block title %}Contact
{% endblock %}
{% block body %}
	<h3 class="text-center">You can contact us here</h3>

{% endblock %}

templates/standard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Travel Agency by Baraa and Michael
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
		<h1 class="text-center">Our Destinations</h1>
		<ul>
			{% for location in locations %}

				<li>Location:{{location.lName}}, Price:{{location.price}}, Description
					{{location.description}}
				</li>
			{% endfor %}

		</ul>


		This friendly message is coming from:
		<ul>
			<li>Your controller at
				<code>
					<a href="{{ 'C:/xampp/htdocs/Symfony-Projects/Day2/baraa_michael_travel/src/Controller/StandardController.php'|file_link(0) }}">src/Controller/StandardController.php</a>
				</code>
			</li>
			<li>Your template at
				<code>
					<a href="{{ 'C:/xampp/htdocs/Symfony-Projects/Day2/baraa_michael_travel/templates/standard/index.html.twig'|file_link(0) }}">templates/standard/index.html.twig</a>
				</code>
			</li>
		</ul>
	</div>
{% endblock %}

templates/standard/news.html.twig
{% extends 'base.html.twig' %}
{% block title %}News
{% endblock %}
{% block body %}
	<h1 class="text-center">News</h1>
	<p>Here come the news</p>
{% endblock %}